name: Build, Test & Push Multi-Image Pipeline

on:
  push:
    branches: [ "master", "main" ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # ------------------------------
      # 1. Checkout repository
      # ------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ------------------------------
      # 2. Login to GHCR
      # ------------------------------
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ------------------------------
      # 3. Build loader image (no push)
      # ------------------------------
      - name: Build loader image
        uses: docker/build-push-action@v5
        with:
          context: ./loader
          file: ./loader/Dockerfile
          push: false
          load: true                  # Needed so GHA can run container locally for tests
          tags: |
            ghcr.io/${{ github.repository }}/loader:latest

      # ------------------------------
      # 4. Test loader image (curl)
      # ------------------------------
      - name: Smoke-test loader
        run: |
          docker run -d --name test_loader -p 5000:5000 ghcr.io/${{ github.repository }}/loader:latest
          echo "Waiting for loader..."
          sleep 5

          echo "Testing endpoint..."
          curl -f http://localhost:5000 || (echo "Loader failed!" && docker logs test_loader && exit 1)

          docker stop test_loader
          docker rm test_loader

      # ------------------------------
      # 5. Build worker image (no push)
      # ------------------------------
      - name: Build worker image
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          file: ./worker/Dockerfile
          push: false
          load: true
          tags: |
            ghcr.io/${{ github.repository }}/worker:latest

      # ------------------------------
      # 6. Test worker image (curl)
      # ------------------------------
      - name: Smoke-test worker
        run: |
          docker run -d --name test_worker -p 5001:5001 ghcr.io/${{ github.repository }}/worker:latest
          echo "Waiting for worker..."
          sleep 5

          echo "Testing endpoint..."
          curl -f http://localhost:5001 || (echo "Worker failed!" && docker logs test_worker && exit 1)

          docker stop test_worker
          docker rm test_worker

      # ------------------------------
      # 7. Push loader image
      # ------------------------------
      - name: Push loader image
        uses: docker/build-push-action@v5
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        with:
          context: ./loader
          file: ./loader/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/loader:latest
            ghcr.io/${{ github.repository }}/loader:${{ github.sha }}

      # ------------------------------
      # 8. Push worker image
      # ------------------------------
      - name: Push worker image
        uses: docker/build-push-action@v5
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        with:
          context: ./worker
          file: ./worker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/worker:latest
            ghcr.io/${{ github.repository }}/worker:${{ github.sha }}

